### ISSUE TITLE
FileBot Xpra can't select multiple folders to load

### ISSUE THREAD

**Issue by KnifeFed** [filebot/filebot-docker#10]
When doing `Load -> Select Folder` you can only select one folder. If you repeat the process to add another folder, it overwrites the previous selection, meaning there's no way to process multiple folders at once. Is there a fix or way around this? Selecting multiple _files_ works fine.

**Comment by rednoah** [comment]
You can configure FileBot with a different `FileDialog` implementation:
https://www.filebot.net/forums/viewtopic.php?t=3913

However, the `GtkFileChooserDialog` that is used by default is definitely the best UX, even if it doesn't support folder multi-selection.

**Comment by KnifeFed** [comment]
Thanks, I changed it to Swing and it works fine.
