### ISSUE TITLE
Filebot watcher don‘t process files

### ISSUE THREAD

**Issue by Tim2309** [filebot/filebot-docker#15]
Hello
I run the filebot warcher on a synology and get the following log:

Waiting 120 seconds for changes to settle down…
/volume1/Downloads/EXTRACTED/Movie/Movie.mkv was modified less than 10 seconds ago
Processing deferred until next change...

After the last line nothing happens, whats wrong with my container?

**Comment by rednoah** [comment]
`Processing deferred until next change...` means that nothing will be processed this time around. But when you add another file, then another round will start and then everything get processed together.

`/volume1/Downloads/EXTRACTED/Movie/Movie.mkv was modified less than 10 seconds ago` means that it is very possible that this file is currently being written, and if you were to process this file now, you'd be processing a half-written file.

    Do make sure that files are moved into the watch folder instantly with atomic move (i.e. instant move within the same file system) and not slowly over time with copy+delete move. If you use copy+delete move then filebot may end up processing partially moved / copied files.

Please read this thread for details:
https://www.filebot.net/forums/viewtopic.php?t=13038

**Comment by Tim2309** [comment]
I increased the cool down time from 120 to 300 now it work without any other changes

**Comment by rednoah** [comment]
I see. It's `600` by default, so it would have worked by default I suppose. Let's leave it at that then.
