### ISSUE TITLE
armhf support for docker images

### ISSUE THREAD

**Issue by blair-morrison** [filebot/filebot-docker#16]
The current images are targeting/tagged for arm64 and amd64 systems. It would be great if armhf could also be supported, so older single board computers could be used with the same docker images. Considering that this architecture is supported in the universal installer it should not be much of a lift hopefully.

Also wanted to add its great to see the variants of these containers so well supported. I had been using a different [image](https://hub.docker.com/r/jlesage/filebot) as I was not aware these existed. I would prefer to use an image straight from the main developer! Thanks again for the great software.

**Comment by rednoah** [comment]
Sorry, `armhf` support is not planned. I would recommend the portable package (i.e. not docker) for either old devices or low-end devices.

**Comment by blair-morrison** [comment]
Thanks for feedback, I will consider both those options. Cheers
