### ISSUE TITLE
Login for XPRA version

### ISSUE THREAD

**Issue by Just4Link** [filebot/filebot-docker#17]
Is there a env i can set, to force a login with password to access filebot? Feels bad when anyone can edit files who knows the ip address in the network.

**Comment by rednoah** [comment]
You'd usual set things up behind a reverse proxy which takes care of certificates and authentication. XPRA itself can probably configured to require some sort of authentication, but you'd have to read the docs for that:
https://xpra.org/

You can pass custom options via the `$XPRA_OPTS` environment variable.

**Comment by rednoah** [comment]
Try this:
```
--env XPRA_OPTS="--auth=password:value=YOURPASSWORD"
```
See https://xpra.org/manual.html for details.

**Comment by rednoah** [comment]
I tried a few things.

This will work:
```
-e XPRA_AUTH="password:value=YOURPASSWORD"
```

**Comment by Just4Link** [comment]
Thanks for the fast answer! That does the trick. Keep up the good work, thanks.
