### ISSUE TITLE
Version tag for dokcer images

### ISSUE THREAD

**Issue by RogerSik** [filebot/filebot-docker#20]
Would be cool to have version tags like

```
docker pull rednoah/filebot:node-5.1.2
# or
docker pull rednoah/filebot-node:5.1.2
```

otherwise 
- it is tricky to determine on which version problems arrive 
- if the docker container is on the newest version
- difficult to do troubleshooting with an older version

**Comment by rednoah** [comment]
Unfortunately, not planned. That would add a multiplier to the number of docker containers we have to maintain. You should always use the latest version anyway. The container on docker hub is always the latest version, so the same command will always run the latest version automatically, updated by docker whenever a newer image is available.

Did you run into any particular issue? If so, please report the issue in the forums:
https://www.filebot.net/forums/viewforum.php?f=6

That said, the community is welcome to maintain version-specific docker containers as older binaries are available:
https://get.filebot.net/filebot/

**Comment by RogerSik** [comment]
Sorry for late reply @rednoah.

The reason i want a version tag is, that currently in my Kubernetes Node i need to redownload every time the latest image when recreating the container. With about 400 MB it takes some time. And the other more important reason is that im not able to detect if there version changes.

With flux i have scanner which checks for new image tags and recreate the container it. Which is not working because latest is never chaging.

**Comment by RogerSik** [comment]
Personally i would also be fine if there is only node and node-version-tag and older version-tag are getting pruned. If is not wished that there is possible to chaging to older version.

**Comment by RogerSik** [comment]
If this is still not wished / planned im fine when this issue get closed.

**Comment by rednoah** [comment]
We still prefer to only have one latest image on Docker Hub for the sake of simplicity.
