### ISSUE TITLE
xpra copy past from windows chrome to filebot not working 

### ISSUE THREAD

**Issue by devildant** [filebot/filebot-docker#25]
hello, 

i try to copy/past (expression) from windows to filebot (chrome => xpra), but not working

![image](https://github.com/filebot/filebot-docker/assets/8700106/86c5ae7f-ad2b-4f8d-b814-fcb58bc71917)

**Comment by rednoah** [comment]
What does the `Format Editor` say? You'll want to prototype custom formats in the `Format Editor` so you can get instant feedback.

**Comment by devildant** [comment]
i cannot CTRL+V copy & paste, also i try right click => paste same result, doesn't work

**Comment by devildant** [comment]
![demo](https://github.com/filebot/filebot-docker/assets/8700106/3b8835ee-97c3-42a5-8e9f-5f40efbad55a)

**Comment by rednoah** [comment]
Is `Clipboard` access enabled?

![Screenshot 2024-05-08 at 23 43 02](https://github.com/filebot/filebot-docker/assets/1589068/05544dc1-c077-4398-9d26-4f85b86914b2)

**Comment by devildant** [comment]
> Is `Clipboard` access enabled?
> 
> ![Screenshot 2024-05-08 at 23 43 02](https://private-user-images.githubusercontent.com/1589068/329063952-05544dc1-c077-4398-9d26-4f85b86914b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMDUzODEsIm5iZiI6MTcxNTIwNTA4MSwicGF0aCI6Ii8xNTg5MDY4LzMyOTA2Mzk1Mi0wNTU0NGRjMS1jMDc3LTQzOTgtOWQyNi00Zjg1Yjg2OTE0YjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDhUMjE1MTIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2NiNzJmNTJiYjcwOGEzMWVmNTBmYjg4ZDMxZjdkOGUyYWJjMzllNWQzMDIyMDQ2YTlkZTAzZGNmZThmZjYyNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.7KsW76dx3AoJmz1mWRPbKK8luxnE0zIHPW9DcTdbCwE)

well seen !
Chrome blocks access to the clipboard, if the connection is not HTTPS, and it is impossible to activate it :(
using reverse proxy with HTTPS, it's work.
Chrome tires me...

thanks
