### ISSUE TITLE
Allow End User to choose the action type for the watcher

### ISSUE THREAD

**Issue by donicrosby** [filebot/filebot-docker#3]
Currently the watcher file only duplicates the file found as an action, I don't want to have multiple copies of the data on my SAN. Allow the end user to decide what action they would like the AMC script to perform.

**Comment by rednoah** [comment]
The `filebot-watcher` script allows you to pass in arbitrary `filebot` option:
https://github.com/filebot/filebot-docker/blob/master/filebot-watcher#L15

If you want `move`, then just add `--action move` to explicitly specify that.

Having said that, `duplicate` will `reflink` or `hardlink` by default, and thus most likely no data is copied:
https://en.wikipedia.org/wiki/Hard_link#Example
