### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by mbaric1** [filebot/filebot-docker#7]
Raspberry Pi 2 - LibreELEC 9.2.6
Linux 4.19.127 #1 SMP Sun Oct 25 08:49:28 EDT 2020 armv7l GNU/Linux
Docker version 18.09.7

Executed command:
```
docker run --rm -it -v /media/ssd/media:/volume1 -v /media/ssd/filebot:/data rednoah/filebot -script fn:sysinfo
```

Error:
```
Unable to find image 'rednoah/filebot:latest' locally
latest: Pulling from rednoah/filebot
f22ccc0b8772: Pull complete
3cf8fb62ba5f: Pull complete
e80c964ece6a: Pull complete
b57ba660415e: Pull complete
c6847402f046: Pull complete
Digest: sha256:524d4132541da4a4c68af8f96f86f4d44cf46097bdaa24d6f05ef69a6dee185b
Status: Downloaded newer image for rednoah/filebot:latest
**standard_init_linux.go:211: exec user process caused "exec format error"
failed to resize tty, using default size**
```

Thanks!

UPDATE:
Same issue happening with filebot-node

**Comment by rednoah** [comment]
`DockerHub` is `x86_64` only. If you need `aarch64` images, then you will need to build them yourself.

**Comment by rednoah** [comment]
If there is a way to instruct `DockerHub` to build `aarch64` images as well, then I'm happy to accept pull requests for that.

**Comment by mbaric1** [comment]
@rednoah Thanks for the response.

 I built own image, but need to solve memory and mediainfo issues.
